vars:
    BUNDLE_ID:
        default: com.josexs.ct
    PACKAGE_NAME:
        default: com.josexs.ct

platforms:
    ios:
        targets:
            App:
                bundleId: $BUNDLE_ID

                entitlements:
                    - com.apple.developer.associated-domains:
                          ['applinks:carstournaments.com']
    android:
        packageName: $PACKAGE_NAME
