export const routes = {
  about: 'about',
  account: 'tab/account',
  car: 'car/:id',
  calendar: 'tab/calendar',
  cars: 'tab/cars',
  home: '',
  inscriptions: 'inscriptions/:id',
  login: 'login',
  myData: 'my-data',
  myGarage: 'my-garage',
  myGarageCreate: 'my-garage/create',
  myGarageOne: 'my-garage/one/:id',
  myInscriptions: 'my-inscriptions',
  myLikes: 'my-likes',
  pairing: 'pairing/:id',
  privaciPolicy: 'privacy-policy',
  ranking: 'ranking',
  register: 'register',
  rounds: 'rounds/:id',
  tab: 'tab',
  tournament: 'tournament/:id',
  tournaments: 'tab/tournaments',
};
